(()=>{const p=new URLSearchParams(location.search);const v=['a','b','c'].includes(p.get('retning'))?p.get('retning'):'a';document.body.className='direction-'+v;document.querySelectorAll('[data-variant]').forEach(a=>{a.setAttribute('aria-current',a.dataset.variant===v?'true':'false')});const h=document.querySelector('h1[data-a]');if(h)h.innerHTML=h.dataset[v];document.querySelectorAll('.next-project,.site-header nav a').forEach(a=>{if(/(husoy|horten)\.html$/.test(a.getAttribute('href')))a.href+='?retning='+v});if(v==='b'){const main=document.querySelector('main'),work=document.querySelector('.work'),intro=document.querySelector('.story-intro');if(main&&work&&intro)main.insertBefore(work,intro)}if(v==='c'){const main=document.querySelector('main'),intro=document.querySelector('.story-intro'),process=document.querySelector('.process');if(main&&intro&&process)main.insertBefore(process,intro)}// Utkast: ingen analyseverktøy eller innsending. Kontaktlenker åpner brukerens telefon/e-post.
})();
document.addEventListener('DOMContentLoaded',()=>{
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 let observer;
 const revealAll=()=>{observer?.disconnect();document.querySelectorAll('.reveal-pending').forEach(e=>e.classList.add('reveal-visible'))};
 if(!reduced.matches&&'IntersectionObserver' in window){observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('reveal-visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.section-heading,.chapter,.story-intro,.detail,.process-inner,.result,.contact-person,.project-card,.proposal').forEach(e=>{if(e.getBoundingClientRect().top>innerHeight){e.classList.add('reveal-pending');observer.observe(e)}});reduced.addEventListener('change',()=>{if(reduced.matches)revealAll()});addEventListener('beforeprint',revealAll)}
 const progress=document.querySelector('.reading-progress');let ticking=false;const update=()=>{const total=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.transform='scaleX('+Math.min(1,Math.max(0,total>0?scrollY/total:0))+')';ticking=false};addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(update)}},{passive:true});addEventListener('resize',update);update();
 const share=document.querySelector('.share-button');share?.addEventListener('click',async()=>{const url=new URL(location.href);url.hash='';const status=document.querySelector('.share-status');try{await navigator.clipboard.writeText(url.href);share.textContent='Lenke kopiert ✓';if(status)status.textContent='Lenken er klar til å deles.';setTimeout(()=>{share.textContent='Kopier lenke ↗';if(status)status.textContent=''},3000)}catch{if(status)status.textContent='Kopier nettadressen fra adresselinjen.';share.textContent='Kopier fra adresselinjen'}});
 const viewer=document.querySelector('.image-viewer');let opener;document.querySelectorAll('.image-frame').forEach(button=>button.addEventListener('click',()=>{if(!viewer)return;opener=button;const source=button.querySelector('img');viewer.querySelector('img').src=source.src;viewer.querySelector('img').alt=source.alt;viewer.querySelector('p').textContent=button.closest('figure').querySelector('figcaption').textContent;viewer.showModal()}));viewer?.querySelector('.viewer-close').addEventListener('click',()=>viewer.close());viewer?.addEventListener('click',event=>{if(event.target===viewer){const b=viewer.getBoundingClientRect();if(event.clientX<b.left||event.clientX>b.right||event.clientY<b.top||event.clientY>b.bottom)viewer.close()}});viewer?.addEventListener('close',()=>opener?.focus());
});
